name: nowtrack
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.0.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  flutter_sound: ^9.0.0
  image_picker: ^1.1.2
  video_player: ^2.0.0
  fl_chart: ^0.71.0
  flutter_animate: ^4.0.0
  flutter_hooks: ^0.21.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  hive_generator: ^1.0.0
  build_web_compilers: ^3.0.0

flutter:
  uses-material-design: true
